### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by r100gs** [rusty-dev/mopidy-deezer#1]
Hello,

when I try installing the mopidy plug-in I get the error message:

Processing /home/pi/mopidy/mopidy-deezer
    Complete output from command python setup.py egg_info:
    error in Mopidy-Deezer setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "u'>= 0.7.9'"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ym3Dm_-build

What ca I do?

Best regards,
Stefan

**Comment by rusty-dev** [comment]
Yep, there was a error in setup.py syntax, it's working now, thanks for your feedback.

**Comment by r100gs** [comment]
THX, its working!
