### ISSUE TITLE
Gaps in tracks

### ISSUE THREAD

**Issue by jjok** [rusty-dev/mopidy-deezer#10]
Quite often recently I find that playback goes silent for several seconds during a track. I don't think the track pauses. It carries on playing, but silent.

**Comment by jjok** [comment]
This started happening a lot for a while. The last week it seems to be happening a lot less. I wonder if it is a problem with Deezer, rather than with the extension?

I'll just close this if the problem goes away.

**Comment by rusty-dev** [comment]
I tested it a while back on my desktop, couldn't reproduce. Perhaps you're running on Raspberry Pi with not enough processing power (It's doing some heavy decryption while playing)?

**Comment by jjok** [comment]
Ha! That could be the case. I'm using a Pi Zero :)

Maybe I'll see what the resource usage is like. Thanks.

**Comment by jjok** [comment]
Mopidy uses around 14% CPU on a Pi Zero when playing from Deezer, and about 40% RAM.

I didn't issue didn't occur while I was watching the stats. I'll see if I can find out what's happening if it occurs again.

**Comment by jjok** [comment]
I've also noticed that the first second or so of each track is usually cut off. I don't know if this is related.

**Comment by jjok** [comment]
I'll assume that these issues were environment-related. I haven't noticed it happening much recently. And I haven't noticed the tracks being cut off at the beginning, although I've mostly been listening to podcasts, rather than music recently.
