### ISSUE TITLE
Account information

### ISSUE THREAD

**Issue by Shellfishgene** [rusty-dev/mopidy-deezer#11]
Hi!
How do I enter my Deezer account information? I tried to use username and password settings in the [deezer] part of the mopidy.conf, like for the spotify plugin, but that doesn't work it seems.

**Comment by jjok** [comment]
Hi. You have to enter your user ID  `user_id = 123`. It's just not that easy to find your ID. You can do it by signing in to deezer.com then looking at the source of the page. Let me know if you need more help.
We could do with something more user friendly.

**Comment by jjok** [comment]
And we need to update the README.

**Comment by Shellfishgene** [comment]
Thanks, it works now. Searching in the deezer page source for   "USER_ID":   will go to the number.

**Comment by jjok** [comment]
Let's keep this open as a reminder to update the documentation.
