### ISSUE TITLE
Segmentation fault on pip install

### ISSUE THREAD

**Issue by jbonina** [rusty-dev/mopidy-deezer#25]
I'm installing the Deezer plugin on mopidy, but I get a Segmentation fault error:

pip install -U git+https://github.com/rusty-dev/mopidy-deezer.git
Collecting git+https://github.com/rusty-dev/mopidy-deezer.git
  Cloning https://github.com/rusty-dev/mopidy-deezer.git to /tmp/pip-bA2dpJ-build
Collecting setuptools (from Mopidy-Deezer==0.2.0)
  Using cached setuptools-38.2.4-py2.py3-none-any.whl
Collecting simplejson (from Mopidy-Deezer==0.2.0)
Collecting pycrypto>=2.6.0 (from Mopidy-Deezer==0.2.0)
Collecting eyed3==0.8 (from Mopidy-Deezer==0.2.0)
  Using cached eyeD3-0.8-py2.py3-none-any.whl
Collecting Mopidy>=2.0 (from Mopidy-Deezer==0.2.0)
  Using cached Mopidy-2.1.0-py2.py3-none-any.whl
Collecting Pykka>=1.1 (from Mopidy-Deezer==0.2.0)
  Using cached Pykka-1.2.1-py2.py3-none-any.whl
Collecting six (from eyed3==0.8->Mopidy-Deezer==0.2.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting requests>=2.0 (from Mopidy>=2.0->Mopidy-Deezer==0.2.0)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting tornado>=3.2 (from Mopidy>=2.0->Mopidy-Deezer==0.2.0)
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0->Mopidy>=2.0->Mopidy-Deezer==0.2.0)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.0->Mopidy>=2.0->Mopidy-Deezer==0.2.0)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0->Mopidy>=2.0->Mopidy-Deezer==0.2.0)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0->Mopidy>=2.0->Mopidy-Deezer==0.2.0)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting singledispatch (from tornado>=3.2->Mopidy>=2.0->Mopidy-Deezer==0.2.0)
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=3.2->Mopidy>=2.0->Mopidy-Deezer==0.2.0)
  Using cached backports_abc-0.5-py2.py3-none-any.whl
Installing collected packages: setuptools, simplejson, pycrypto, six, eyed3, urllib3, idna, chardet, certifi, requests, singledispatch, backports-abc, tornado, Pykka, Mopidy, Mopidy-Deezer
Segmentation fault

Anybody have any idea of what to do? This is on Debian Linux.

**Comment by jbonina** [comment]
I managed to overcome that by issuing the command:
pip install --no-cache-dir  git+https://github.com/rusty-dev/mopidy-deezer.git

But now, plugin doesn't show up as enabled.

mopidy.conf has these:
[deezer]
enabled = true
username = **********
password = ***********

**Comment by rusty-dev** [comment]
I'm assuming you restarted mopidy after modifying config, if not, do that.
Also, there are no `username` and `password` parameters, only `enabled` and `user_id`.
Other than that, some UI backends might not display the plugin properly, try another one just to be sure.

**Comment by jbonina** [comment]
I found something further:
Disabled extension deezer: eyed3==0.8 required, but found eyeD3 0.8.1 at /home/play/.local/lib/python2.7/site-packages

I guess I must find a way to force installation of eyed3==0.8

**Comment by rusty-dev** [comment]
just run `pip install -U eyed3==0.8`

**Comment by jbonina** [comment]
Thanks, that worked.

Now to this one, it should be simple to find:
  File "/usr/local/lib/python2.7/dist-packages/eyed3/utils/__init__.py", line 23, in <module>
    import pathlib
ImportError: No module named pathlib

**Comment by jbonina** [comment]
Ditto:
 pip install pathlib

**Comment by rusty-dev** [comment]
so you got it working then?

**Comment by jbonina** [comment]
Yup!

The wrong eyeD3 version was the originating problem.
