### ISSUE TITLE
User integration

### ISSUE THREAD

**Issue by jjok** [rusty-dev/mopidy-deezer#3]
Hi. Have you started looking in to the user integration?

I might give it a go.

**Comment by rusty-dev** [comment]
Hello. No, I haven't started user integration yet, the current state of plugin satisfied all of my needs and I've been lazy to improve it further. If you feel like you can implement it - go ahead, I'll be happy to help and accept your changes.

**Comment by rusty-dev** [comment]
Merged your current changes, I also added current user's Flow.

**Comment by jjok** [comment]
Hey. Thanks for merging that.

Currently, when I go to **Deezer > Artists > Some Artist** I just get a long list of all the tracks that are on albums that the artist is on. I'd like it so that you get the same view as when you do a search and click on the artist (artist biography at the top with a picture, then a list of all their albums below).
Do you know how I would do that? I couldn't work it out. I'm using Moped as the frontend, by the way.

Thanks.

**Comment by jjok** [comment]
Hmmm.... mopidy-gmusic seems to do the same thing for displaying an artist. Does that mean it's a frontend thing?

**Comment by rusty-dev** [comment]
It happens [here](https://github.com/rusty-dev/mopidy-deezer/blob/master/mopidy_deezer/library.py#L51), because I'm returning a list of track refs, but this is what's required... I would expect an uri like `deezer:artist:99999` to go to lookup instead of browse, but it does not. Looks like a weird API thing, I don't see a quick way to fix this.

**Comment by rusty-dev** [comment]
Here's [browse](http://mopidy.readthedocs.io/en/latest/api/core/#mopidy.core.LibraryController.browse) documentation, it really looks like full links should go into lookup instead of browse. I've tried musicbox and moped frontends, they both work like this.

**Comment by jjok** [comment]
In Moped, when you do a search then click on an artist, it goes to this URL `/#/artist/deezer:artist:8633/Anberlin`, which gives you the nice artist page.

This is the URL when I browse artists `/#/library/deezer%253Aartist%253A8633/Deezer%252FArtists%252FAnberlin`. (Not sure what's up with all the encoding)

Do you think this is a frontend issue?

**Comment by rusty-dev** [comment]
I cannot know for sure, but it may be mopidy core issue, because when I tried to return `Ref.artist` record from `browse`, clicking on an artist still brought me back into browse with the same uri. But it also may be that there's a way to switch from `browse` to `lookup` that we don't know about.

**Comment by jjok** [comment]
Looks like this is what we're talking about. https://github.com/mopidy/mopidy/issues/738

**Comment by rusty-dev** [comment]
Yep, I think it is. The issue two years old though, looks like they never got to implementing it after all.
