### ISSUE TITLE
Albums missing tracks

### ISSUE THREAD

**Issue by jjok** [rusty-dev/mopidy-deezer#9]
When I go to Albums, then select an album, only up to 10 tracks are listed, when the album has more tracks.

**Comment by rusty-dev** [comment]
Strange how I didn't notice that earlier, perhaps they changed their api recently, but I might be wrong.
In any case, I just fixed that.

**Comment by jjok** [comment]
Oh, nice! I was going to look into it myself. Thanks!

**Comment by jjok** [comment]
Yeah, I think I would've noticed that too. They must have changed the default value.
I seem to remember trying it with and without `nb` and it didn't make a difference, so I left it out,
